//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Dispatch.Scripts
{
    public static class OrderEvents
    {
        public static string OrderChargeEvent = "OrderChargeEvent";
        public static string StopDurationUpdated = "StopDurationUpdated";
        public static string HubAdded = "HubAdded";
        public static string OrderCreated = "OrderCreated";
        public static string OrderCancelled = "OrderCancelled";
        public static string ProofOfPickupAdded = "ProofOfPickupAdded";
        public static string ProofOfDeliveryAdded = "ProofOfDeliveryAdded";
        public static string TrackedOrderItemsAdded = "TrackedOrderItemsAdded";
        public static string OrderExceptionCodesAdded = "OrderExceptionCodesAdded";
        public static string OrderExceptionCodesRemoved = "OrderExceptionCodesRemoved";
        public static string ItemExceptionCodesAdded = "ItemExceptionCodesAdded";
        public static string ItemExceptionCodesRemoved = "ItemExceptionCodesRemoved";
        public static string OrderDispatchedToDriver = "OrderDispatchedToDriver";
        public static string DriverUnassigned = "DriverUnassigned";
        public static string OrderAcceptedByDriver = "OrderAcceptedByDriver";
        public static string OrderDismissedByDriver = "OrderDismissedByDriver";
        public static string DriverArrivedAtPickup = "DriverArrivedAtPickup";
        public static string OrderPickedUp = "OrderPickedUp";
        public static string DriverArrivedAtDelivery = "DriverArrivedAtDelivery";
        public static string OrderDelivered = "OrderDelivered";
        public static string OrderPutOnHold = "OrderPutOnHold";
        public static string OrderReleased = "OrderReleased";
        public static string OrderReactivated = "OrderReactivated";
        public static string MultiSegmentOrderReactivated = "MultiSegmentOrderReactivated";
        public static string PickupAddressUpdated = "PickupAddressUpdated";
        public static string DropoffAddressUpdated = "DropoffAddressUpdated";
        public static string PickupLocationUpdated = "PickupLocationUpdated";
        public static string DistanceUpdated = "DistanceUpdated";
        public static string DropoffLocationUpdated = "DropoffLocationUpdated";
        public static string PickupFromTimeUpdated = "PickupFromTimeUpdated";
        public static string PickupToTimeUpdated = "PickupToTimeUpdated";
        public static string PickupWindowUpdated = "PickupWindowUpdated";
        public static string DropoffFromTimeUpdated = "DropoffFromTimeUpdated";
        public static string DropoffToTimeUpdated = "DropoffToTimeUpdated";
        public static string DeliveryWindowUpdated = "DeliveryWindowUpdated";
        public static string DriverNotesUpdated = "DriverNotesUpdated";
        public static string PickupNotesUpdated = "PickupNotesUpdated";
        public static string DeliveryNotesUpdated = "DeliveryNotesUpdated";
        public static string InternalNotesUpdated = "InternalNotesUpdated";
        public static string ContactInfoUpdated = "ContactInfoUpdated";
        public static string PickupContactInfoUpdated = "PickupContactInfoUpdated";
        public static string DropoffContactInfoUpdated = "DropoffContactInfoUpdated";
        public static string ValidationErrorsAdded = "ValidationErrorsAdded";
        public static string ValidationErrorsResolved = "ValidationErrorsResolved";
        public static string ReceivedByUpdated = "ReceivedByUpdated";
        public static string ReceivedOnPickupFromUpdated = "ReceivedOnPickupFromUpdated";
        public static string StatusPickedUpDateUpdated = "StatusPickedUpDateUpdated";
        public static string StatusDeliveredDateUpdated = "StatusDeliveredDateUpdated";
        public static string HasSignatureUpdated = "HasSignatureUpdated";
        public static string HasPickupSignatureUpdated = "HasPickupSignatureUpdated";
        public static string VehicleTypeIdUpdated = "VehicleTypeIdUpdated";
        public static string AttributeIdsUpdated = "AttributeIdsUpdated";
        public static string AllowPartialCollectOnDeliveryUpdated = "AllowPartialCollectOnDeliveryUpdated";
        public static string AllowPartialCollectOnPickupUpdated = "AllowPartialCollectOnPickupUpdated";
        public static string NotificationsDataUpdated = "NotificationsDataUpdated";
        public static string ServiceLevelIdUpdated = "ServiceLevelIdUpdated";
        public static string ReferenceNumbersUpdated = "ReferenceNumbersUpdated";
        public static string CollectOnDeliveryUpdated = "CollectOnDeliveryUpdated";
        public static string CollectOnPickupUpdated = "CollectOnPickupUpdated";
        public static string RequireIdentityValidationUpdated = "RequireIdentityValidationUpdated";
        public static string RequireIdentityValidationOnPickupUpdated = "RequireIdentityValidationOnPickupUpdated";
        public static string WebhookUrlUpdated = "WebhookUrlUpdated";
        public static string ReadyAtUpdated = "ReadyAtUpdated";
        public static string DeliveryChargeAdded = "DeliveryChargeAdded";
        public static string DeliveryChargeUpdated = "DeliveryChargeUpdated";
        public static string ExtraFeeChargeAdded = "ExtraFeeChargeAdded";
        public static string ExtraFeeChargeUpdated = "ExtraFeeChargeUpdated";
        public static string FuelSurchargeUpdatedOnDeliveryCharge = "FuelSurchargeUpdatedOnDeliveryCharge";
        public static string FuelSurchargeUpdatedOnExtraFeeCharge = "FuelSurchargeUpdatedOnExtraFeeCharge";
        public static string FuelSurchargeUpdatedOnCharge = "FuelSurchargeUpdatedOnCharge";
        public static string ChargeRemoved = "ChargeRemoved";
        public static string ChargesRemoved = "ChargesRemoved";
        public static string DriverAddedToPayout = "DriverAddedToPayout";
        public static string DriverPayoutsUpdated = "DriverPayoutsUpdated";
        public static string DriverPayoutsSetManually = "DriverPayoutsSetManually";
        public static string OrderPayoutUpdated = "OrderPayoutUpdated";
        public static string OrderAddedToInvoice = "OrderAddedToInvoice";
        public static string OrderPayoutSettled = "OrderPayoutSettled";
        public static string OrderPayoutUnsettled = "OrderPayoutUnsettled";
        public static string ZonesAdded = "ZonesAdded";
        public static string PickupZonesUpdated = "PickupZonesUpdated";
        public static string DeliveryZonesUpdated = "DeliveryZonesUpdated";
        public static string AutoDispatchEnabled = "AutoDispatchEnabled";
        public static string AutoDispatchDisabled = "AutoDispatchDisabled";
        public static string OrderItemsAdded = "OrderItemsAdded";
        public static string OrderItemsUpdated = "OrderItemsUpdated";
        public static string OrderItemsRemoved = "OrderItemsRemoved";
        public static string OrderScannedAtCheckpoint = "OrderScannedAtCheckpoint";
        public static string OrderAddedToRoute = "OrderAddedToRoute";
        public static string OrderRemovedFromRoute = "OrderRemovedFromRoute";
        public static string OrderAttachmentAdded = "OrderAttachmentAdded";
        public static string OrderAttachmentUploaded = "OrderAttachmentUploaded";
        public static string OrderAttachmentTypeEdited = "OrderAttachmentTypeEdited";
        public static string OrderAttachmentNoteEdited = "OrderAttachmentNoteEdited";
        public static string OrderAttachmentIncludeWithInvoiceFlagUpdated = "OrderAttachmentIncludeWithInvoiceFlagUpdated";
        public static string OrderAttachmentDeleted = "OrderAttachmentDeleted";
        public static string OrderAttachmentsDeleted = "OrderAttachmentsDeleted";
        public static string OrderRemovedFromInvoice = "OrderRemovedFromInvoice";
        public static string OrderMarkedAsReadyForInvoicing = "OrderMarkedAsReadyForInvoicing";
        public static string OrderMarkedAsVerifyBeforeInvoicing = "OrderMarkedAsVerifyBeforeInvoicing";
        public static string OrderMarkedAsReadyForSettlement = "OrderMarkedAsReadyForSettlement";
        public static string OrderMarkedAsVerifyBeforeSettlement = "OrderMarkedAsVerifyBeforeSettlement";
        public static string OrderUserFieldsAdded = "OrderUserFieldsAdded";
        public static string OrderUserFieldsUpdated = "OrderUserFieldsUpdated";
        public static string OrderUserFieldsRemoved = "OrderUserFieldsRemoved";
        public static string OrderWorkflowUpdated = "OrderWorkflowUpdated";
        public static string PackageValidationOptionUpdated = "PackageValidationOptionUpdated";
        public static string GenerateProofOfDeliveryOnDeliveryUpdated = "GenerateProofOfDeliveryOnDeliveryUpdated";
        public static string OrderWorkflowStepUpdated = "OrderWorkflowStepUpdated";
        public static string CustomerInfosUpdated = "CustomerInfosUpdated";
        public static string AccountIdUpdated = "AccountIdUpdated";
        public static string OrderAnonymized = "OrderAnonymized";
        public static string SegmentLinkedToOrder = "SegmentLinkedToOrder";
        public static string SegmentPickupAddressUpdated = "SegmentPickupAddressUpdated";
        public static string SegmentDeliveryAddressUpdated = "SegmentDeliveryAddressUpdated";
    }
}